version: "3.9"
name: "nginx-node"

services:
  nginx:
    image: nginx:1.23.4
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/mnt/Working's Disk/docker-nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/mnt/Working's Disk/docker-nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/mnt/Working's Disk/docker-nginx/srv:/srv"
      - "/mnt/Working's Disk/docker-nginx/html:/usr/share/nginx/html"
