version: "3.9"
name: "nginx"

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx-certbot
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/mnt/Working's Disk/docker-nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/mnt/Working's Disk/docker-nginx/srv:/srv"
      - "/mnt/Working's Disk/docker-nginx/sites-available:/etc/nginx/sites-available"
      - "/mnt/Working's Disk/docker-nginx/nginx_secrets:/etc/letsencrypt"
